package com.emploverse.backend.model;

public enum DepartmentName {
    HR,
    IT,
    FINANCE,
    SALES,
    MARKETING,
    ENGINEERING,
    LEGAL,
    OPERATIONS,
    ADMINISTRATION,
    CUSTOMER_SERVICE,
    PROCUREMENT,
    RESEARCH_AND_DEVELOPMENT,
    QUALITY_ASSURANCE,
    PRODUCT_MANAGEMENT,
    BUSINESS_DEVELOPMENT,
    COMMUNICATIONS,
    PUBLIC_RELATIONS,
    SUPPLY_CHAIN,
    TRAINING_AND_DEVELOPMENT
}
